### ISSUE TITLE
Hovering course details can prevent bars from being clickable

### ISSUE THREAD

**Issue by pagorgis** [pagorgis/ivis-group-project#10]
![image](https://user-images.githubusercontent.com/25200291/76025369-1644dc00-5f2d-11ea-9d41-7f5f737aa3dd.png)

When hovering over the bars in the course details stacked bar chart, the tooltip sort of hides over bars sometimes which prevents them from being clickable. Thus you can't press on the teacher you might want to see in detailed teacher view.

**Comment by CeciliaXZQ** [comment]
Hovering or clicking on a rectangle can provide some "highlight effect" like broader border width/darken colour, so it gives the more intuitive feeling of selecting

**Comment by pagorgis** [comment]
Sort of solved by changing select('body') to select(#theidforthevisualization). Not sure if it can be done better.
